create table ibm.pilsisko (
   id_beer NUMBER GENERATED by default on null as IDENTITY, 
   beer_name varchar2(32) not null,
   alcohol number(4,2) default 5.5, 
   top_fermentation number(1) default 0,
   CONSTRAINT customers_pk PRIMARY KEY (id_beer));

insert into pilsisko (beer_name, alcohol) values ('Pinta Atak Chmielu',6.0);
insert into ibm.pilsisko (beer_name, alcohol) values ('Brewmeister Snake Venom', 67.5);
insert into ibm.pilsisko (beer_name, alcohol, top_fermentation) values ('Pinta Hazy Morning', 4.4, 1);